import type { Metadata } from "next";
import "./globals.css";
import { inter } from "../fonts";
import Header from "@/components/Header_";

export const metadata: Metadata = {
  title: "lifridraws",
  description: "Generated by create next app",
};

interface RootLayoutProps {
  children: React.ReactNode;
  params: {
    locale: string;
  };
}
export default function RootLayout({
  children,
  params: { locale },
}: Readonly<RootLayoutProps>) {
  return (
    <html lang={locale}>
      <body className={inter.variable}>
        <header>
          <Header />
        </header>
        <main>{children}</main>
      </body>
    </html>
  );
}
